#!/bin/sh
#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Start wesnothd in the foreground with the config generated by the module.
# wesnothd ignores SIGTERM/SIGINT (it only reloads on SIGHUP), so a container
# stop is turned into the admin command "shut_down now" written to the server
# FIFO (fifo_path in the config, created by the server itself). Replays and
# the ban list live in the data volume.

cfg="${WESNOTHD_CONFIG:-/etc/wesnothd/wesnothd.cfg}"
fifo="${WESNOTHD_FIFO:-/var/lib/wesnothd/socket}"
mkdir -p /var/lib/wesnothd/replays
[ -f "$cfg" ] || { echo "config $cfg missing" >&2; exit 1; }
# a stale regular file at the FIFO path (e.g. a command written while the
# server was down) would make wesnothd's mkfifo fail: remove anything that is
# not a named pipe
if [ -e "$fifo" ] && [ ! -p "$fifo" ]; then
    echo "removing stale non-FIFO $fifo" >&2
    rm -f "$fifo"
fi

echo "wesnothd $(wesnothd -V 2>&1 | tail -1) starting on port 15000 with $cfg" >&2
wesnothd -c "$cfg" -p 15000 "$@" &
pid=$!

shutdown() {
    echo "stop requested: sending 'shut_down now' to $fifo" >&2
    if [ -p "$fifo" ]; then
        # the write blocks if nobody reads the FIFO: give up after a few seconds
        ( printf 'shut_down now\n' > "$fifo" ) & writer=$!
        ( sleep 5; kill "$writer" 2>/dev/null ) & killer=$!
        wait "$writer" 2>/dev/null; kill "$killer" 2>/dev/null
    fi
    # fall back to a plain kill if the server is still around
    ( sleep 10; kill -9 "$pid" 2>/dev/null ) &
}
trap shutdown TERM INT

# "wait" returns early (128+signal) when a trapped signal arrives: wait again
# until wesnothd has really exited, so the container stops with its status.
wait "$pid"
status=$?
while kill -0 "$pid" 2>/dev/null; do
    wait "$pid"
    status=$?
done
echo "wesnothd exited with status $status" >&2
exit "$status"
